package localscan

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/config"
	"github.com/srz-zumix/go-gh-extension/pkg/logger"
)

// HookNames lists the git hooks that can be managed by this tool.
var HookNames = []string{"pre-commit", "pre-push"}

// DefaultInstallHookNames lists the hooks installed when none are requested.
// Scanning on push is enough to stop a secret from reaching the remote, and
// avoids the cost of scanning on every commit.
var DefaultInstallHookNames = []string{"pre-push"}

// hookMarker identifies hook scripts generated by this tool.
const hookMarker = "gh-secure-kit:secret-scanning-local"

// hookBackupSuffix is appended to an existing hook moved aside on install.
const hookBackupSuffix = ".gh-secure-kit.bak"

// HookState describes the installation state of a single git hook.
type HookState string

const (
	// HookStateInstalled means the hook exists and was generated by this tool.
	HookStateInstalled HookState = "installed"
	// HookStateNotInstalled means no hook file exists.
	HookStateNotInstalled HookState = "not_installed"
	// HookStateUnmanaged means a hook file exists but was not generated by this tool.
	HookStateUnmanaged HookState = "unmanaged"
)

// HookStatus reports the state of a single git hook.
type HookStatus struct {
	Name  string    `json:"name"`
	Path  string    `json:"path"`
	State HookState `json:"state"`
}

// InstallHookOptions controls how an existing, unmanaged hook file is handled.
type InstallHookOptions struct {
	Force  bool
	Backup bool
	// LogLevel, when set, is passed as --log-level to the check command the
	// generated hook runs.
	LogLevel string
}

// ResolveHookNames validates the requested hook names, returning all
// supported hooks when none are given.
func ResolveHookNames(names []string) ([]string, error) {
	if len(names) == 0 {
		return slices.Clone(HookNames), nil
	}
	for _, n := range names {
		if !slices.Contains(HookNames, n) {
			return nil, fmt.Errorf("unsupported hook %q, expected one of %s", n, strings.Join(HookNames, ", "))
		}
	}
	return slices.Clone(names), nil
}

// HooksDir resolves the directory git reads hooks from for the repository at
// repoPath, honoring the core.hooksPath configuration.
func HooksDir(repoPath string) (string, error) {
	repo, err := git.PlainOpenWithOptions(repoPath, &git.PlainOpenOptions{DetectDotGit: true})
	if err != nil {
		return "", fmt.Errorf("failed to open git repository at %q: %w", repoPath, err)
	}
	worktree, err := repo.Worktree()
	if err != nil {
		return "", fmt.Errorf("failed to resolve worktree for %q: %w", repoPath, err)
	}
	root := worktree.Filesystem.Root()

	cfg, err := repo.ConfigScoped(config.SystemScope)
	if err != nil {
		return "", fmt.Errorf("failed to read git configuration for %q: %w", repoPath, err)
	}
	if hooksPath := cfg.Raw.Section("core").Option("hooksPath"); hooksPath != "" {
		if filepath.IsAbs(hooksPath) {
			return hooksPath, nil
		}
		return filepath.Join(root, hooksPath), nil
	}

	gitDir, err := resolveGitDir(root)
	if err != nil {
		return "", err
	}
	return filepath.Join(gitDir, "hooks"), nil
}

// InstallHook writes the hook script for name into dir and returns its path.
func InstallHook(dir, name string, opts InstallHookOptions) (string, error) {
	script, err := hookScript(name, opts.LogLevel)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("failed to create hooks directory %q: %w", dir, err)
	}

	path := filepath.Join(dir, name)
	state, err := hookStateAt(path)
	if err != nil {
		return "", err
	}
	if state == HookStateUnmanaged {
		switch {
		case opts.Backup:
			if err := os.Rename(path, path+hookBackupSuffix); err != nil {
				return "", fmt.Errorf("failed to back up existing hook %q: %w", path, err)
			}
		case !opts.Force:
			return "", fmt.Errorf("hook %q already exists and is not managed by gh-secure-kit, use --force to overwrite it or --backup to move it aside", path)
		}
	}

	// Write to a temporary file and rename it over the destination so we never
	// follow an existing symlink (which could place hook content outside dir)
	// and never leave a partially written hook behind.
	tmp, err := os.CreateTemp(dir, name+".tmp-*")
	if err != nil {
		return "", fmt.Errorf("failed to create temporary hook file in %q: %w", dir, err)
	}
	tmpPath := tmp.Name()
	defer func() { _ = os.Remove(tmpPath) }()
	if _, err := tmp.WriteString(script); err != nil {
		_ = tmp.Close()
		return "", fmt.Errorf("failed to write hook %q: %w", path, err)
	}
	if err := tmp.Close(); err != nil {
		return "", fmt.Errorf("failed to write hook %q: %w", path, err)
	}
	if err := os.Chmod(tmpPath, 0o755); err != nil {
		return "", fmt.Errorf("failed to make hook %q executable: %w", path, err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return "", fmt.Errorf("failed to install hook %q: %w", path, err)
	}
	return path, nil
}

// UninstallHook removes the hook script for name from dir and reports whether
// a hook was removed. A hook not generated by this tool is only removed when
// force is true.
func UninstallHook(dir, name string, force bool) (bool, error) {
	if !slices.Contains(HookNames, name) {
		return false, fmt.Errorf("unsupported hook %q, expected one of %s", name, strings.Join(HookNames, ", "))
	}
	path := filepath.Join(dir, name)
	state, err := hookStateAt(path)
	if err != nil {
		return false, err
	}
	switch state {
	case HookStateNotInstalled:
		return false, nil
	case HookStateUnmanaged:
		if !force {
			return false, fmt.Errorf("hook %q is not managed by gh-secure-kit, use --force to remove it", path)
		}
	}
	if err := os.Remove(path); err != nil {
		return false, fmt.Errorf("failed to remove hook %q: %w", path, err)
	}
	return true, nil
}

// HookStatuses reports the state of each of the given hooks in dir.
func HookStatuses(dir string, names []string) ([]HookStatus, error) {
	statuses := make([]HookStatus, 0, len(names))
	for _, name := range names {
		path := filepath.Join(dir, name)
		state, err := hookStateAt(path)
		if err != nil {
			return nil, err
		}
		statuses = append(statuses, HookStatus{Name: name, Path: path, State: state})
	}
	return statuses, nil
}

// hookHeader is the comment block that identifies a generated hook script.
func hookHeader(name string) string {
	return fmt.Sprintf(`#!/bin/sh
# %s
# Managed by: gh secure-kit secret-scanning local hook install
# Remove with: gh secure-kit secret-scanning local hook uninstall %s`, hookMarker, name)
}

// hookScript renders the shell script installed for the given hook. logLevel,
// when not empty, is passed as --log-level to the check command.
func hookScript(name, logLevel string) (string, error) {
	logFlag, err := hookLogLevelFlag(logLevel)
	if err != nil {
		return "", err
	}
	switch name {
	case "pre-commit":
		return hookHeader(name) + `
exec gh secure-kit secret-scanning local check` + logFlag + ` --staged
`, nil
	case "pre-push":
		// Git passes the pushed refs on stdin as
		// "<local ref> <local sha> <remote ref> <remote sha>" lines, and the
		// destination remote name as $1. Scan the exact commits being pushed so
		// a secret on any pushed branch (not just the checked-out HEAD) is
		// caught. A zero remote sha means a new ref, a zero local sha means a
		// deletion. For a new ref, exclude only the destination remote so a
		// commit that lives only on a different remote is still scanned.
		return hookHeader(name) + `
zero=0000000000000000000000000000000000000000
remote_name="$1"
while read -r local_ref local_sha remote_ref remote_sha; do
	[ "$local_sha" = "$zero" ] && continue
	if [ "$remote_sha" = "$zero" ]; then
		gh secure-kit secret-scanning local check` + logFlag + ` --unpushed --rev "$local_sha" --remote "$remote_name" || exit 1
	else
		gh secure-kit secret-scanning local check` + logFlag + ` --rev-range "$remote_sha..$local_sha" || exit 1
	fi
done
exit 0
`, nil
	default:
		return "", fmt.Errorf("unsupported hook %q, expected one of %s", name, strings.Join(HookNames, ", "))
	}
}

// hookLogLevelFlag renders the --log-level flag embedded in a generated hook,
// rejecting any value that is not a known log level so nothing arbitrary is
// written into the script.
func hookLogLevelFlag(logLevel string) (string, error) {
	if logLevel == "" {
		return "", nil
	}
	if _, err := logger.GetLogLevel(logLevel); err != nil {
		return "", fmt.Errorf("unsupported log level %q, expected one of %s", logLevel, strings.Join(logger.LogLevel, ", "))
	}
	return " --log-level " + strings.ToLower(logLevel), nil
}

// hookStateAt classifies the hook file at path.
func hookStateAt(path string) (HookState, error) {
	// A symlink is never a hook this tool generated; treat it as unmanaged so
	// it is not silently overwritten (and is never followed on write).
	if info, err := os.Lstat(path); err == nil && info.Mode()&os.ModeSymlink != 0 {
		return HookStateUnmanaged, nil
	}
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return HookStateNotInstalled, nil
	}
	if err != nil {
		return "", fmt.Errorf("failed to read hook %q: %w", path, err)
	}
	// Match the marker only as its own comment line so an unrelated hook that
	// merely mentions the marker text is not mistaken for a generated hook.
	if hasMarkerLine(string(data)) {
		return HookStateInstalled, nil
	}
	return HookStateUnmanaged, nil
}

// hasMarkerLine reports whether content contains the generated marker on its
// own comment line.
func hasMarkerLine(content string) bool {
	markerLine := "# " + hookMarker
	for _, line := range strings.Split(content, "\n") {
		if strings.TrimRight(line, "\r") == markerLine {
			return true
		}
	}
	return false
}

// resolveGitDir returns the git directory for a worktree root, following the
// gitdir pointer used by linked worktrees and submodules.
func resolveGitDir(root string) (string, error) {
	dotGit := filepath.Join(root, ".git")
	info, err := os.Stat(dotGit)
	if err != nil {
		return "", fmt.Errorf("failed to locate git directory at %q: %w", dotGit, err)
	}
	if info.IsDir() {
		return dotGit, nil
	}
	data, err := os.ReadFile(dotGit)
	if err != nil {
		return "", fmt.Errorf("failed to read git directory pointer %q: %w", dotGit, err)
	}
	pointer, ok := strings.CutPrefix(strings.TrimSpace(string(data)), "gitdir:")
	if !ok {
		return "", fmt.Errorf("unexpected git directory pointer format in %q", dotGit)
	}
	gitDir := strings.TrimSpace(pointer)
	if !filepath.IsAbs(gitDir) {
		gitDir = filepath.Join(root, gitDir)
	}
	// In a linked worktree the pointer targets a per-worktree admin directory
	// (.git/worktrees/<name>), but git runs hooks from the common git
	// directory. Resolve commondir so hooks are installed where git looks.
	commonData, err := os.ReadFile(filepath.Join(gitDir, "commondir"))
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return gitDir, nil
		}
		return "", fmt.Errorf("failed to read commondir pointer in %q: %w", gitDir, err)
	}
	commonDir := strings.TrimSpace(string(commonData))
	if !filepath.IsAbs(commonDir) {
		commonDir = filepath.Join(gitDir, commonDir)
	}
	return filepath.Clean(commonDir), nil
}
