package localscan

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/config"
)

// HookNames lists the git hooks that can be managed by this tool.
var HookNames = []string{"pre-commit", "pre-push"}

// DefaultInstallHookNames lists the hooks installed when none are requested.
// Scanning on push is enough to stop a secret from reaching the remote, and
// avoids the cost of scanning on every commit.
var DefaultInstallHookNames = []string{"pre-push"}

// hookMarker identifies hook scripts generated by this tool.
const hookMarker = "gh-secure-kit:secret-scanning-local"

// hookBackupSuffix is appended to an existing hook moved aside on install.
const hookBackupSuffix = ".gh-secure-kit.bak"

// HookState describes the installation state of a single git hook.
type HookState string

const (
	// HookStateInstalled means the hook exists and was generated by this tool.
	HookStateInstalled HookState = "installed"
	// HookStateNotInstalled means no hook file exists.
	HookStateNotInstalled HookState = "not_installed"
	// HookStateUnmanaged means a hook file exists but was not generated by this tool.
	HookStateUnmanaged HookState = "unmanaged"
)

// HookStatus reports the state of a single git hook.
type HookStatus struct {
	Name  string    `json:"name"`
	Path  string    `json:"path"`
	State HookState `json:"state"`
}

// InstallHookOptions controls how an existing, unmanaged hook file is handled.
type InstallHookOptions struct {
	Force  bool
	Backup bool
}

// ResolveHookNames validates the requested hook names, returning all
// supported hooks when none are given.
func ResolveHookNames(names []string) ([]string, error) {
	if len(names) == 0 {
		return slices.Clone(HookNames), nil
	}
	for _, n := range names {
		if !slices.Contains(HookNames, n) {
			return nil, fmt.Errorf("unsupported hook %q, expected one of %s", n, strings.Join(HookNames, ", "))
		}
	}
	return slices.Clone(names), nil
}

// HooksDir resolves the directory git reads hooks from for the repository at
// repoPath, honoring the core.hooksPath configuration.
func HooksDir(repoPath string) (string, error) {
	repo, err := git.PlainOpenWithOptions(repoPath, &git.PlainOpenOptions{DetectDotGit: true})
	if err != nil {
		return "", fmt.Errorf("failed to open git repository at %q: %w", repoPath, err)
	}
	worktree, err := repo.Worktree()
	if err != nil {
		return "", fmt.Errorf("failed to resolve worktree for %q: %w", repoPath, err)
	}
	root := worktree.Filesystem.Root()

	cfg, err := repo.ConfigScoped(config.SystemScope)
	if err != nil {
		return "", fmt.Errorf("failed to read git configuration for %q: %w", repoPath, err)
	}
	if hooksPath := cfg.Raw.Section("core").Option("hooksPath"); hooksPath != "" {
		if filepath.IsAbs(hooksPath) {
			return hooksPath, nil
		}
		return filepath.Join(root, hooksPath), nil
	}

	gitDir, err := resolveGitDir(root)
	if err != nil {
		return "", err
	}
	return filepath.Join(gitDir, "hooks"), nil
}

// InstallHook writes the hook script for name into dir and returns its path.
func InstallHook(dir, name string, opts InstallHookOptions) (string, error) {
	script, err := hookScript(name)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("failed to create hooks directory %q: %w", dir, err)
	}

	path := filepath.Join(dir, name)
	state, err := hookStateAt(path)
	if err != nil {
		return "", err
	}
	if state == HookStateUnmanaged {
		switch {
		case opts.Backup:
			if err := os.Rename(path, path+hookBackupSuffix); err != nil {
				return "", fmt.Errorf("failed to back up existing hook %q: %w", path, err)
			}
		case !opts.Force:
			return "", fmt.Errorf("hook %q already exists and is not managed by gh-secure-kit, use --force to overwrite it or --backup to move it aside", path)
		}
	}

	if err := os.WriteFile(path, []byte(script), 0o755); err != nil {
		return "", fmt.Errorf("failed to write hook %q: %w", path, err)
	}
	// WriteFile does not change the mode of an existing file.
	if err := os.Chmod(path, 0o755); err != nil {
		return "", fmt.Errorf("failed to make hook %q executable: %w", path, err)
	}
	return path, nil
}

// UninstallHook removes the hook script for name from dir and reports whether
// a hook was removed. A hook not generated by this tool is only removed when
// force is true.
func UninstallHook(dir, name string, force bool) (bool, error) {
	if !slices.Contains(HookNames, name) {
		return false, fmt.Errorf("unsupported hook %q, expected one of %s", name, strings.Join(HookNames, ", "))
	}
	path := filepath.Join(dir, name)
	state, err := hookStateAt(path)
	if err != nil {
		return false, err
	}
	switch state {
	case HookStateNotInstalled:
		return false, nil
	case HookStateUnmanaged:
		if !force {
			return false, fmt.Errorf("hook %q is not managed by gh-secure-kit, use --force to remove it", path)
		}
	}
	if err := os.Remove(path); err != nil {
		return false, fmt.Errorf("failed to remove hook %q: %w", path, err)
	}
	return true, nil
}

// HookStatuses reports the state of each of the given hooks in dir.
func HookStatuses(dir string, names []string) ([]HookStatus, error) {
	statuses := make([]HookStatus, 0, len(names))
	for _, name := range names {
		path := filepath.Join(dir, name)
		state, err := hookStateAt(path)
		if err != nil {
			return nil, err
		}
		statuses = append(statuses, HookStatus{Name: name, Path: path, State: state})
	}
	return statuses, nil
}

// hookScript renders the shell script installed for the given hook.
func hookScript(name string) (string, error) {
	var target string
	switch name {
	case "pre-commit":
		target = "--staged"
	case "pre-push":
		target = "--unpushed"
	default:
		return "", fmt.Errorf("unsupported hook %q, expected one of %s", name, strings.Join(HookNames, ", "))
	}
	return fmt.Sprintf(`#!/bin/sh
# %s
# Managed by: gh secure-kit secret-scanning local hook install
# Remove with: gh secure-kit secret-scanning local hook uninstall %s
exec gh secure-kit secret-scanning local check %s
`, hookMarker, name, target), nil
}

// hookStateAt classifies the hook file at path.
func hookStateAt(path string) (HookState, error) {
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return HookStateNotInstalled, nil
	}
	if err != nil {
		return "", fmt.Errorf("failed to read hook %q: %w", path, err)
	}
	if strings.Contains(string(data), hookMarker) {
		return HookStateInstalled, nil
	}
	return HookStateUnmanaged, nil
}

// resolveGitDir returns the git directory for a worktree root, following the
// gitdir pointer used by linked worktrees and submodules.
func resolveGitDir(root string) (string, error) {
	dotGit := filepath.Join(root, ".git")
	info, err := os.Stat(dotGit)
	if err != nil {
		return "", fmt.Errorf("failed to locate git directory at %q: %w", dotGit, err)
	}
	if info.IsDir() {
		return dotGit, nil
	}
	data, err := os.ReadFile(dotGit)
	if err != nil {
		return "", fmt.Errorf("failed to read git directory pointer %q: %w", dotGit, err)
	}
	pointer, ok := strings.CutPrefix(strings.TrimSpace(string(data)), "gitdir:")
	if !ok {
		return "", fmt.Errorf("unexpected git directory pointer format in %q", dotGit)
	}
	gitDir := strings.TrimSpace(pointer)
	if !filepath.IsAbs(gitDir) {
		gitDir = filepath.Join(root, gitDir)
	}
	return gitDir, nil
}
