// Package hook implements the "secret-scanning local hook" commands, which
// manage the git hooks that run local secret scanning.
package hook

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/srz-zumix/gh-secure-kit/internal/localscan"
	"github.com/srz-zumix/go-gh-extension/pkg/logger"
)

// NewInstallCmd returns the secret-scanning local hook install command
func NewInstallCmd() *cobra.Command {
	var (
		path   string
		force  bool
		backup bool
	)

	cmd := &cobra.Command{
		Use:   "install [pre-commit|pre-push]...",
		Short: "Install git hooks that run local secret scanning",
		Long: `Install git hooks that run 'secret-scanning local check' before a commit or a push.
Only the pre-push hook is installed when no hook name is given, which is enough to stop a secret from reaching the remote.
The pre-commit hook scans staged changes and the pre-push hook scans unpushed commits, aborting the operation when a secret is found.
An existing hook that was not generated by this tool is kept unless --force or --backup is given.`,
		ValidArgs: localscan.HookNames,
		Args:      cobra.OnlyValidArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				args = localscan.DefaultInstallHookNames
			}
			names, err := localscan.ResolveHookNames(args)
			if err != nil {
				return err
			}
			dir, err := localscan.HooksDir(path)
			if err != nil {
				return fmt.Errorf("failed to resolve the git hooks directory: %w", err)
			}
			for _, name := range names {
				hookPath, err := localscan.InstallHook(dir, name, localscan.InstallHookOptions{Force: force, Backup: backup})
				if err != nil {
					return fmt.Errorf("failed to install the %s hook: %w", name, err)
				}
				logger.Info("installed git hook", "hook", name, "path", hookPath)
			}
			return nil
		},
	}

	f := cmd.Flags()
	f.StringVar(&path, "path", ".", "The repository path to install the hooks into")
	f.BoolVar(&force, "force", false, "Overwrite an existing hook that is not managed by gh-secure-kit")
	f.BoolVar(&backup, "backup", false, "Move an existing hook aside to <hook>.gh-secure-kit.bak before installing")
	cmd.MarkFlagsMutuallyExclusive("force", "backup")

	return cmd
}
