package hook

import (
	"fmt"

	"github.com/cli/cli/v2/pkg/cmdutil"
	"github.com/spf13/cobra"
	"github.com/srz-zumix/gh-secure-kit/internal/localscan"
	"github.com/srz-zumix/go-gh-extension/pkg/render"
)

// StatusOptions holds the format exporter for the status command output.
type StatusOptions struct {
	Exporter cmdutil.Exporter
}

// NewStatusCmd returns the secret-scanning local hook status command
func NewStatusCmd() *cobra.Command {
	var path string
	opts := &StatusOptions{}

	cmd := &cobra.Command{
		Use:   "status",
		Short: "Show the installation state of the local secret scanning git hooks",
		Long: `Show whether each supported git hook is installed.
A hook is reported as 'installed' when it was generated by this tool, 'unmanaged' when a different hook script is present, and 'not_installed' when no hook file exists.`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			dir, err := localscan.HooksDir(path)
			if err != nil {
				return fmt.Errorf("failed to resolve the git hooks directory: %w", err)
			}
			statuses, err := localscan.HookStatuses(dir, localscan.HookNames)
			if err != nil {
				return fmt.Errorf("failed to inspect the git hooks: %w", err)
			}

			renderer := render.NewRenderer(opts.Exporter)
			if err := renderHookStatuses(renderer, statuses); err != nil {
				return fmt.Errorf("failed to render the git hook statuses: %w", err)
			}
			return nil
		},
	}

	cmd.Flags().StringVar(&path, "path", ".", "The repository path to inspect")
	cmdutil.AddFormatFlags(cmd, &opts.Exporter)

	return cmd
}

// renderHookStatuses renders hook statuses as a table, or via the configured
// exporter (e.g. JSON) when one is set.
func renderHookStatuses(r *render.Renderer, statuses []localscan.HookStatus) error {
	if r.HasExporter() {
		return r.RenderExportedData(statuses)
	}
	table := r.NewTableWriter([]string{"Hook", "State", "Path"})
	for _, s := range statuses {
		table.Append([]string{s.Name, string(s.State), s.Path})
	}
	return table.Render()
}
