package hook

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/srz-zumix/gh-secure-kit/internal/localscan"
	"github.com/srz-zumix/go-gh-extension/pkg/logger"
)

// NewUninstallCmd returns the secret-scanning local hook uninstall command
func NewUninstallCmd() *cobra.Command {
	var (
		path  string
		force bool
	)

	cmd := &cobra.Command{
		Use:   "uninstall [pre-commit|pre-push]...",
		Short: "Remove git hooks that run local secret scanning",
		Long: `Remove the git hooks installed by 'secret-scanning local hook install'.
Every supported hook is removed when no hook name is given.
A hook that was not generated by this tool is kept unless --force is given.`,
		ValidArgs: localscan.HookNames,
		Args:      cobra.OnlyValidArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			names, err := localscan.ResolveHookNames(args)
			if err != nil {
				return err
			}
			dir, err := localscan.HooksDir(path)
			if err != nil {
				return fmt.Errorf("failed to resolve the git hooks directory: %w", err)
			}
			for _, name := range names {
				removed, err := localscan.UninstallHook(dir, name, force)
				if err != nil {
					return fmt.Errorf("failed to uninstall the %s hook: %w", name, err)
				}
				if removed {
					logger.Info("removed git hook", "hook", name)
				} else {
					logger.Info("git hook is not installed, nothing to remove", "hook", name)
				}
			}
			return nil
		},
	}

	f := cmd.Flags()
	f.StringVar(&path, "path", ".", "The repository path to remove the hooks from")
	f.BoolVar(&force, "force", false, "Remove an existing hook even when it is not managed by gh-secure-kit")

	return cmd
}
